name: Eslint
on:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: "dummy"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Eslint
        run: yarn install --prefer-offline

      - name: Success
        run: exit 0