name: Release CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn install --prefer-offline

      - name: Run tests
        run: yarn validate

      - name: Update package json - pt. 1
        run: 'sed "s/version\": \".*\"/version\": \"${GITHUB_REF##*/}\"/g" package.json > package.json.temp'

      - name: Update package json - pt. 2
        run: cat package.json.temp > package.json; rm package.json.temp

      - name: Commit and push
        run: |
          git config --global user.name '⚙️ Release bot'
          git config --global user.email 'raffaele-abramini@users.noreply.github.com'
          git fetch
          git checkout -b main origin/main
          git commit -am "v${GITHUB_REF##*/}"
          git push

      - name: Add .npmrc
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
