name: Release CI
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn install --prefer-offline

      - name: Run UI tests
        run: yarn jest

      - name: Run E2E tests
        run: yarn start:e2eApp & yarn cypress:run --browser chrome

      - name: Build files
        run: yarn build

      - name: Update package json - pt. 1
        run: 'sed "s/version\": \".*\"/version\": \"${GITHUB_REF##*/}\"/g" package.json > package.json.temp'

      - name: Update package json - pt. 2
        run: cat package.json.temp > package.json; rm package.json.temp

      - name: Commit and push
        run: |
          git config --global user.name '⚙️ Release bot'
          git config --global user.email 'raffaele-abramini@users.noreply.github.com'
          git fetch
          git checkout -b main origin/main
          git commit -am "v${GITHUB_REF##*/}"
          git push

      - name: Add .npmrc
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
