# This is a basic workflow to help you get started with Actions

name: Update json CI

# Controls when the action will run.
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: "dummy"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Runs cypress
        run: 'yarn cypress:run'

      - name: Success
        run: 'echo "success"'