# This is a basic workflow to help you get started with Actions

name: Update json CI

# Controls when the action will run.
on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: "dummy"

    steps:
      - uses: actions/checkout@v2
      - name: Update package json - pt. 1
        run: 'sed "s/version\": \".*\"/version\": \"${GITHUB_REF##*/}\"/g" package.json > package.json.temp'
      - name: Update package json - pt. 2
        run: cat package.json.temp > package.json; rm package.json.temp
      - name: Commit and push
        run: |
          git config --global user.name '⚙️ Release bot'
          git config --global user.email 'raffaele-abramini@users.noreply.github.com'
          git commit -am "v${GITHUB_REF##*/}"
          git push