# This is a basic workflow to help you get started with Actions

name: Update json CI

# Controls when the action will run.
on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: "dummy"

    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq
      - name: Update package json
        run: originalVersion=`cat ./package.json` \
          content=`jq --arg v ${GITHUB_REF##*/} '.version = $v' <<<"$originalVersion"` \
          echo $content \
          $content > package.json
