name: Validate on push
on:
  push
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: "dummy"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install modules
        run: yarn install --prefer-offline

      - name: Run E2E tests
        run: yarn start & yarn cypress:run --browser chrome

      - name: Success
        run: exit 0